// flow-typed signature: 39dfde1cc0ec499d60411bb72abb1053
// flow-typed version: <<STUB>>/@mdx-js/loader_v^0.16.6/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdx-js/loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdx-js/loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@mdx-js/loader/index' {
  declare module.exports: $Exports<'@mdx-js/loader'>;
}
declare module '@mdx-js/loader/index.js' {
  declare module.exports: $Exports<'@mdx-js/loader'>;
}
