// flow-typed signature: f139b14b246532101ca9e42ce8bf2ffd
// flow-typed version: <<STUB>>/@mdx-js/mdx_v^0.16.4/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdx-js/mdx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdx-js/mdx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mdx-js/mdx/md-ast-to-mdx-ast' {
  declare module.exports: any;
}

declare module '@mdx-js/mdx/mdx-ast-to-mdx-hast' {
  declare module.exports: any;
}

declare module '@mdx-js/mdx/mdx-hast-to-jsx' {
  declare module.exports: any;
}

declare module '@mdx-js/mdx/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mdx-js/mdx/index' {
  declare module.exports: $Exports<'@mdx-js/mdx'>;
}
declare module '@mdx-js/mdx/index.js' {
  declare module.exports: $Exports<'@mdx-js/mdx'>;
}
declare module '@mdx-js/mdx/md-ast-to-mdx-ast.js' {
  declare module.exports: $Exports<'@mdx-js/mdx/md-ast-to-mdx-ast'>;
}
declare module '@mdx-js/mdx/mdx-ast-to-mdx-hast.js' {
  declare module.exports: $Exports<'@mdx-js/mdx/mdx-ast-to-mdx-hast'>;
}
declare module '@mdx-js/mdx/mdx-hast-to-jsx.js' {
  declare module.exports: $Exports<'@mdx-js/mdx/mdx-hast-to-jsx'>;
}
declare module '@mdx-js/mdx/util.js' {
  declare module.exports: $Exports<'@mdx-js/mdx/util'>;
}
