// flow-typed signature: 30f9d18bc4bdb1ace0f6ed8382655331
// flow-typed version: <<STUB>>/babel-loader-lerna-cra_v^0.1.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-loader-lerna-cra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-loader-lerna-cra' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-loader-lerna-cra/bootstrap' {
  declare module.exports: any;
}

declare module 'babel-loader-lerna-cra/findLoader' {
  declare module.exports: any;
}

declare module 'babel-loader-lerna-cra/getLernaRoot' {
  declare module.exports: any;
}

declare module 'babel-loader-lerna-cra/loadConfig' {
  declare module.exports: any;
}

declare module 'babel-loader-lerna-cra/override' {
  declare module.exports: any;
}

declare module 'babel-loader-lerna-cra/webpack.config.replacement' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-loader-lerna-cra/bootstrap.js' {
  declare module.exports: $Exports<'babel-loader-lerna-cra/bootstrap'>;
}
declare module 'babel-loader-lerna-cra/findLoader.js' {
  declare module.exports: $Exports<'babel-loader-lerna-cra/findLoader'>;
}
declare module 'babel-loader-lerna-cra/getLernaRoot.js' {
  declare module.exports: $Exports<'babel-loader-lerna-cra/getLernaRoot'>;
}
declare module 'babel-loader-lerna-cra/loadConfig.js' {
  declare module.exports: $Exports<'babel-loader-lerna-cra/loadConfig'>;
}
declare module 'babel-loader-lerna-cra/override.js' {
  declare module.exports: $Exports<'babel-loader-lerna-cra/override'>;
}
declare module 'babel-loader-lerna-cra/webpack.config.replacement.js' {
  declare module.exports: $Exports<'babel-loader-lerna-cra/webpack.config.replacement'>;
}
