// flow-typed signature: 0870cda25d9bf9fa5d61bd128822c6f9
// flow-typed version: <<STUB>>/chartjs-plugin-datalabels_v0.4.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chartjs-plugin-datalabels'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chartjs-plugin-datalabels' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.min' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-datalabels/rollup.config' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-datalabels/samples/samples' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-datalabels/samples/utils' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-datalabels/src/defaults' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-datalabels/src/hitbox' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-datalabels/src/label' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-datalabels/src/plugin' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-datalabels/src/positioners' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-datalabels/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels'>;
}
declare module 'chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.min.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.min'>;
}
declare module 'chartjs-plugin-datalabels/rollup.config.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/rollup.config'>;
}
declare module 'chartjs-plugin-datalabels/samples/samples.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/samples/samples'>;
}
declare module 'chartjs-plugin-datalabels/samples/utils.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/samples/utils'>;
}
declare module 'chartjs-plugin-datalabels/src/defaults.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/src/defaults'>;
}
declare module 'chartjs-plugin-datalabels/src/hitbox.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/src/hitbox'>;
}
declare module 'chartjs-plugin-datalabels/src/label.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/src/label'>;
}
declare module 'chartjs-plugin-datalabels/src/plugin.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/src/plugin'>;
}
declare module 'chartjs-plugin-datalabels/src/positioners.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/src/positioners'>;
}
declare module 'chartjs-plugin-datalabels/src/utils.js' {
  declare module.exports: $Exports<'chartjs-plugin-datalabels/src/utils'>;
}
