// flow-typed signature: 2ca0218506fedf4472b334c7719e3c21
// flow-typed version: <<STUB>>/chartjs-plugin-zoom_v0.6.6/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chartjs-plugin-zoom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chartjs-plugin-zoom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chartjs-plugin-zoom/chartjs-plugin-zoom' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-zoom/chartjs-plugin-zoom.min' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-zoom/gulpfile' {
  declare module.exports: any;
}

declare module 'chartjs-plugin-zoom/src/chart.zoom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chartjs-plugin-zoom/chartjs-plugin-zoom.js' {
  declare module.exports: $Exports<'chartjs-plugin-zoom/chartjs-plugin-zoom'>;
}
declare module 'chartjs-plugin-zoom/chartjs-plugin-zoom.min.js' {
  declare module.exports: $Exports<'chartjs-plugin-zoom/chartjs-plugin-zoom.min'>;
}
declare module 'chartjs-plugin-zoom/gulpfile.js' {
  declare module.exports: $Exports<'chartjs-plugin-zoom/gulpfile'>;
}
declare module 'chartjs-plugin-zoom/src/chart.zoom.js' {
  declare module.exports: $Exports<'chartjs-plugin-zoom/src/chart.zoom'>;
}
