// flow-typed signature: 4ca9412a2603f069bee86c45ee3c9a46
// flow-typed version: <<STUB>>/earcut_v^2.1.3/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'earcut'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'earcut' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'earcut/dist/earcut.dev' {
  declare module.exports: any;
}

declare module 'earcut/dist/earcut.min' {
  declare module.exports: any;
}

declare module 'earcut/src/earcut' {
  declare module.exports: any;
}

// Filename aliases
declare module 'earcut/dist/earcut.dev.js' {
  declare module.exports: $Exports<'earcut/dist/earcut.dev'>;
}
declare module 'earcut/dist/earcut.min.js' {
  declare module.exports: $Exports<'earcut/dist/earcut.min'>;
}
declare module 'earcut/src/earcut.js' {
  declare module.exports: $Exports<'earcut/src/earcut'>;
}
