// flow-typed signature: 73d1413a9b7e70d83648f189a8dfe6ae
// flow-typed version: <<STUB>>/eslint-config-problems_v^2.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-problems'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-problems' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-problems/internal-eslintrc' {
  declare module.exports: any;
}

declare module 'eslint-config-problems/node10' {
  declare module.exports: any;
}

declare module 'eslint-config-problems/node8' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-problems/index' {
  declare module.exports: $Exports<'eslint-config-problems'>;
}
declare module 'eslint-config-problems/index.js' {
  declare module.exports: $Exports<'eslint-config-problems'>;
}
declare module 'eslint-config-problems/internal-eslintrc.js' {
  declare module.exports: $Exports<'eslint-config-problems/internal-eslintrc'>;
}
declare module 'eslint-config-problems/node10.js' {
  declare module.exports: $Exports<'eslint-config-problems/node10'>;
}
declare module 'eslint-config-problems/node8.js' {
  declare module.exports: $Exports<'eslint-config-problems/node8'>;
}
