// flow-typed signature: ed0cb8cec0aea4fe05a125a1f5945503
// flow-typed version: <<STUB>>/eslint-plugin-import-order-alphabetical_v^0.0.2/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-import-order-alphabetical'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-import-order-alphabetical' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-import-order-alphabetical/importType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import-order-alphabetical/order' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-import-order-alphabetical/importType.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order-alphabetical/importType'>;
}
declare module 'eslint-plugin-import-order-alphabetical/index' {
  declare module.exports: $Exports<'eslint-plugin-import-order-alphabetical'>;
}
declare module 'eslint-plugin-import-order-alphabetical/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order-alphabetical'>;
}
declare module 'eslint-plugin-import-order-alphabetical/order.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order-alphabetical/order'>;
}
