// flow-typed signature: 41e32ef7efadac04ebdbf97d72e22662
// flow-typed version: <<STUB>>/expect_v^24.9.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expect/build-es5' {
  declare module.exports: any;
}

declare module 'expect/build/asymmetricMatchers' {
  declare module.exports: any;
}

declare module 'expect/build/extractExpectedAssertionsErrors' {
  declare module.exports: any;
}

declare module 'expect/build/fakeChalk' {
  declare module.exports: any;
}

declare module 'expect/build' {
  declare module.exports: any;
}

declare module 'expect/build/jasmineUtils' {
  declare module.exports: any;
}

declare module 'expect/build/jestMatchersObject' {
  declare module.exports: any;
}

declare module 'expect/build/matchers' {
  declare module.exports: any;
}

declare module 'expect/build/print' {
  declare module.exports: any;
}

declare module 'expect/build/spyMatchers' {
  declare module.exports: any;
}

declare module 'expect/build/toThrowMatchers' {
  declare module.exports: any;
}

declare module 'expect/build/types' {
  declare module.exports: any;
}

declare module 'expect/build/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expect/build-es5/index' {
  declare module.exports: $Exports<'expect/build-es5'>;
}
declare module 'expect/build-es5/index.js' {
  declare module.exports: $Exports<'expect/build-es5'>;
}
declare module 'expect/build/asymmetricMatchers.js' {
  declare module.exports: $Exports<'expect/build/asymmetricMatchers'>;
}
declare module 'expect/build/extractExpectedAssertionsErrors.js' {
  declare module.exports: $Exports<'expect/build/extractExpectedAssertionsErrors'>;
}
declare module 'expect/build/fakeChalk.js' {
  declare module.exports: $Exports<'expect/build/fakeChalk'>;
}
declare module 'expect/build/index' {
  declare module.exports: $Exports<'expect/build'>;
}
declare module 'expect/build/index.js' {
  declare module.exports: $Exports<'expect/build'>;
}
declare module 'expect/build/jasmineUtils.js' {
  declare module.exports: $Exports<'expect/build/jasmineUtils'>;
}
declare module 'expect/build/jestMatchersObject.js' {
  declare module.exports: $Exports<'expect/build/jestMatchersObject'>;
}
declare module 'expect/build/matchers.js' {
  declare module.exports: $Exports<'expect/build/matchers'>;
}
declare module 'expect/build/print.js' {
  declare module.exports: $Exports<'expect/build/print'>;
}
declare module 'expect/build/spyMatchers.js' {
  declare module.exports: $Exports<'expect/build/spyMatchers'>;
}
declare module 'expect/build/toThrowMatchers.js' {
  declare module.exports: $Exports<'expect/build/toThrowMatchers'>;
}
declare module 'expect/build/types.js' {
  declare module.exports: $Exports<'expect/build/types'>;
}
declare module 'expect/build/utils.js' {
  declare module.exports: $Exports<'expect/build/utils'>;
}
