// flow-typed signature: 7ef87f55b43f8fea9bdc0c053a7ecdcd
// flow-typed version: <<STUB>>/inter-ui_v3.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inter-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inter-ui' {
  declare module.exports: any;
}
