// flow-typed signature: f8156fe0424d1fa70623b1e33cbf8712
// flow-typed version: <<STUB>>/jest-canvas-mock_v^1.1.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-canvas-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-canvas-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-canvas-mock/__tests__/index' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/__tests__/server-side' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/canvas' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/context2d' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/index' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/window' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/src/canvas' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/src/context2d' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/src/index' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/src/window' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-canvas-mock/__tests__/index.js' {
  declare module.exports: $Exports<'jest-canvas-mock/__tests__/index'>;
}
declare module 'jest-canvas-mock/__tests__/server-side.js' {
  declare module.exports: $Exports<'jest-canvas-mock/__tests__/server-side'>;
}
declare module 'jest-canvas-mock/lib/canvas.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/canvas'>;
}
declare module 'jest-canvas-mock/lib/context2d.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/context2d'>;
}
declare module 'jest-canvas-mock/lib/index.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/index'>;
}
declare module 'jest-canvas-mock/lib/window.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/window'>;
}
declare module 'jest-canvas-mock/src/canvas.js' {
  declare module.exports: $Exports<'jest-canvas-mock/src/canvas'>;
}
declare module 'jest-canvas-mock/src/context2d.js' {
  declare module.exports: $Exports<'jest-canvas-mock/src/context2d'>;
}
declare module 'jest-canvas-mock/src/index.js' {
  declare module.exports: $Exports<'jest-canvas-mock/src/index'>;
}
declare module 'jest-canvas-mock/src/window.js' {
  declare module.exports: $Exports<'jest-canvas-mock/src/window'>;
}
