// flow-typed signature: 56d1b49e4c4f9b0b81ef08d125de3e10
// flow-typed version: <<STUB>>/jest-canvas-mock_v^2.0.0-beta.1/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-canvas-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-canvas-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-canvas-mock/lib/canvas' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/classes/CanvasGradient' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/classes/CanvasPattern' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/classes/CanvasRenderingContext2D' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/classes/context2d' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/classes/DOMMatrix' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/classes/ImageBitmap' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/classes/ImageData' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/classes/Path2D' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/classes/TextMetrics' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/mock/createImageBitmap' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/mock/prototype' {
  declare module.exports: any;
}

declare module 'jest-canvas-mock/lib/window' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-canvas-mock/lib/canvas.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/canvas'>;
}
declare module 'jest-canvas-mock/lib/classes/CanvasGradient.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/classes/CanvasGradient'>;
}
declare module 'jest-canvas-mock/lib/classes/CanvasPattern.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/classes/CanvasPattern'>;
}
declare module 'jest-canvas-mock/lib/classes/CanvasRenderingContext2D.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/classes/CanvasRenderingContext2D'>;
}
declare module 'jest-canvas-mock/lib/classes/context2d.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/classes/context2d'>;
}
declare module 'jest-canvas-mock/lib/classes/DOMMatrix.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/classes/DOMMatrix'>;
}
declare module 'jest-canvas-mock/lib/classes/ImageBitmap.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/classes/ImageBitmap'>;
}
declare module 'jest-canvas-mock/lib/classes/ImageData.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/classes/ImageData'>;
}
declare module 'jest-canvas-mock/lib/classes/Path2D.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/classes/Path2D'>;
}
declare module 'jest-canvas-mock/lib/classes/TextMetrics.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/classes/TextMetrics'>;
}
declare module 'jest-canvas-mock/lib/index' {
  declare module.exports: $Exports<'jest-canvas-mock/lib'>;
}
declare module 'jest-canvas-mock/lib/index.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib'>;
}
declare module 'jest-canvas-mock/lib/mock/createImageBitmap.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/mock/createImageBitmap'>;
}
declare module 'jest-canvas-mock/lib/mock/prototype.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/mock/prototype'>;
}
declare module 'jest-canvas-mock/lib/window.js' {
  declare module.exports: $Exports<'jest-canvas-mock/lib/window'>;
}
