// flow-typed signature: 220e888417cd9ade4cd15557a5f573be
// flow-typed version: <<STUB>>/jest-diff_v24.9.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-diff/build/cleanupSemantic' {
  declare module.exports: any;
}

declare module 'jest-diff/build/constants' {
  declare module.exports: any;
}

declare module 'jest-diff/build/diffLines' {
  declare module.exports: any;
}

declare module 'jest-diff/build/diffStrings' {
  declare module.exports: any;
}

declare module 'jest-diff/build/getAlignedDiffs' {
  declare module.exports: any;
}

declare module 'jest-diff/build' {
  declare module.exports: any;
}

declare module 'jest-diff/build/joinAlignedDiffs' {
  declare module.exports: any;
}

declare module 'jest-diff/build/printDiffs' {
  declare module.exports: any;
}

declare module 'jest-diff/build/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-diff/build/cleanupSemantic.js' {
  declare module.exports: $Exports<'jest-diff/build/cleanupSemantic'>;
}
declare module 'jest-diff/build/constants.js' {
  declare module.exports: $Exports<'jest-diff/build/constants'>;
}
declare module 'jest-diff/build/diffLines.js' {
  declare module.exports: $Exports<'jest-diff/build/diffLines'>;
}
declare module 'jest-diff/build/diffStrings.js' {
  declare module.exports: $Exports<'jest-diff/build/diffStrings'>;
}
declare module 'jest-diff/build/getAlignedDiffs.js' {
  declare module.exports: $Exports<'jest-diff/build/getAlignedDiffs'>;
}
declare module 'jest-diff/build/index' {
  declare module.exports: $Exports<'jest-diff/build'>;
}
declare module 'jest-diff/build/index.js' {
  declare module.exports: $Exports<'jest-diff/build'>;
}
declare module 'jest-diff/build/joinAlignedDiffs.js' {
  declare module.exports: $Exports<'jest-diff/build/joinAlignedDiffs'>;
}
declare module 'jest-diff/build/printDiffs.js' {
  declare module.exports: $Exports<'jest-diff/build/printDiffs'>;
}
declare module 'jest-diff/build/types.js' {
  declare module.exports: $Exports<'jest-diff/build/types'>;
}
