// flow-typed signature: e7a6d1d253eb196206515f5319c284b8
// flow-typed version: <<STUB>>/memoize-weak_v^1.0.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memoize-weak'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memoize-weak' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memoize-weak/lib/memoize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memoize-weak/index' {
  declare module.exports: $Exports<'memoize-weak'>;
}
declare module 'memoize-weak/index.js' {
  declare module.exports: $Exports<'memoize-weak'>;
}
declare module 'memoize-weak/lib/memoize.js' {
  declare module.exports: $Exports<'memoize-weak/lib/memoize'>;
}
