// flow-typed signature: ed38bcbf892b54ab78211534e52f77c4
// flow-typed version: <<STUB>>/monaco-editor-webpack-plugin_v1.7.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'monaco-editor-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'monaco-editor-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'monaco-editor-webpack-plugin/features' {
  declare module.exports: any;
}

declare module 'monaco-editor-webpack-plugin/languages' {
  declare module.exports: any;
}

declare module 'monaco-editor-webpack-plugin/loaders/include' {
  declare module.exports: any;
}

declare module 'monaco-editor-webpack-plugin/plugins/AddWorkerEntryPointPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'monaco-editor-webpack-plugin/features.js' {
  declare module.exports: $Exports<'monaco-editor-webpack-plugin/features'>;
}
declare module 'monaco-editor-webpack-plugin/index' {
  declare module.exports: $Exports<'monaco-editor-webpack-plugin'>;
}
declare module 'monaco-editor-webpack-plugin/index.js' {
  declare module.exports: $Exports<'monaco-editor-webpack-plugin'>;
}
declare module 'monaco-editor-webpack-plugin/languages.js' {
  declare module.exports: $Exports<'monaco-editor-webpack-plugin/languages'>;
}
declare module 'monaco-editor-webpack-plugin/loaders/include.js' {
  declare module.exports: $Exports<'monaco-editor-webpack-plugin/loaders/include'>;
}
declare module 'monaco-editor-webpack-plugin/plugins/AddWorkerEntryPointPlugin.js' {
  declare module.exports: $Exports<'monaco-editor-webpack-plugin/plugins/AddWorkerEntryPointPlugin'>;
}
