// flow-typed signature: de25242070deb3ba4bd70e72d05a3ddb
// flow-typed version: <<STUB>>/natsort_v2.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'natsort'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'natsort' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'natsort/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'natsort/lib/index.js' {
  declare module.exports: $Exports<'natsort/lib/index'>;
}
