// flow-typed signature: 75f81a55e36bcd3f331b5c537d94194f
// flow-typed version: <<STUB>>/nearley_v2.15.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nearley'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nearley' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nearley/bin/nearley-railroad' {
  declare module.exports: any;
}

declare module 'nearley/bin/nearley-test' {
  declare module.exports: any;
}

declare module 'nearley/bin/nearley-unparse' {
  declare module.exports: any;
}

declare module 'nearley/bin/nearleyc' {
  declare module.exports: any;
}

declare module 'nearley/lib/compile' {
  declare module.exports: any;
}

declare module 'nearley/lib/generate' {
  declare module.exports: any;
}

declare module 'nearley/lib/lint' {
  declare module.exports: any;
}

declare module 'nearley/lib/nearley-language-bootstrapped' {
  declare module.exports: any;
}

declare module 'nearley/lib/nearley' {
  declare module.exports: any;
}

declare module 'nearley/lib/stream' {
  declare module.exports: any;
}

declare module 'nearley/lib/unparse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nearley/bin/nearley-railroad.js' {
  declare module.exports: $Exports<'nearley/bin/nearley-railroad'>;
}
declare module 'nearley/bin/nearley-test.js' {
  declare module.exports: $Exports<'nearley/bin/nearley-test'>;
}
declare module 'nearley/bin/nearley-unparse.js' {
  declare module.exports: $Exports<'nearley/bin/nearley-unparse'>;
}
declare module 'nearley/bin/nearleyc.js' {
  declare module.exports: $Exports<'nearley/bin/nearleyc'>;
}
declare module 'nearley/lib/compile.js' {
  declare module.exports: $Exports<'nearley/lib/compile'>;
}
declare module 'nearley/lib/generate.js' {
  declare module.exports: $Exports<'nearley/lib/generate'>;
}
declare module 'nearley/lib/lint.js' {
  declare module.exports: $Exports<'nearley/lib/lint'>;
}
declare module 'nearley/lib/nearley-language-bootstrapped.js' {
  declare module.exports: $Exports<'nearley/lib/nearley-language-bootstrapped'>;
}
declare module 'nearley/lib/nearley.js' {
  declare module.exports: $Exports<'nearley/lib/nearley'>;
}
declare module 'nearley/lib/stream.js' {
  declare module.exports: $Exports<'nearley/lib/stream'>;
}
declare module 'nearley/lib/unparse.js' {
  declare module.exports: $Exports<'nearley/lib/unparse'>;
}
