// flow-typed signature: 930be6d7d24e2227c2139357888688c8
// flow-typed version: <<STUB>>/nearley-loader_v^2.0.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nearley-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nearley-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nearley-loader/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nearley-loader/src/index' {
  declare module.exports: $Exports<'nearley-loader/src'>;
}
declare module 'nearley-loader/src/index.js' {
  declare module.exports: $Exports<'nearley-loader/src'>;
}
