// flow-typed signature: 39fe29d51185cbfb67280eee9d1b7b09
// flow-typed version: <<STUB>>/normalize-wheel_v1.0.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-wheel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-wheel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'normalize-wheel/src/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'normalize-wheel/src/isEventSupported' {
  declare module.exports: any;
}

declare module 'normalize-wheel/src/normalizeWheel' {
  declare module.exports: any;
}

declare module 'normalize-wheel/src/UserAgent_DEPRECATED' {
  declare module.exports: any;
}

// Filename aliases
declare module 'normalize-wheel/index' {
  declare module.exports: $Exports<'normalize-wheel'>;
}
declare module 'normalize-wheel/index.js' {
  declare module.exports: $Exports<'normalize-wheel'>;
}
declare module 'normalize-wheel/src/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'normalize-wheel/src/ExecutionEnvironment'>;
}
declare module 'normalize-wheel/src/isEventSupported.js' {
  declare module.exports: $Exports<'normalize-wheel/src/isEventSupported'>;
}
declare module 'normalize-wheel/src/normalizeWheel.js' {
  declare module.exports: $Exports<'normalize-wheel/src/normalizeWheel'>;
}
declare module 'normalize-wheel/src/UserAgent_DEPRECATED.js' {
  declare module.exports: $Exports<'normalize-wheel/src/UserAgent_DEPRECATED'>;
}
