// flow-typed signature: 11cc79fd9dbcf88f0ada5150fc8d4afd
// flow-typed version: <<STUB>>/polygon-generator_v^1.1.2/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polygon-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polygon-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'polygon-generator/polygon' {
  declare module.exports: any;
}

// Filename aliases
declare module 'polygon-generator/polygon.js' {
  declare module.exports: $Exports<'polygon-generator/polygon'>;
}
