// flow-typed signature: fa49d2586233027bc14d4947f5650a85
// flow-typed version: <<STUB>>/quickhull3d_v2.0.4/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'quickhull3d'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'quickhull3d' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'quickhull3d/dist/Face' {
  declare module.exports: any;
}

declare module 'quickhull3d/dist/HalfEdge' {
  declare module.exports: any;
}

declare module 'quickhull3d/dist' {
  declare module.exports: any;
}

declare module 'quickhull3d/dist/QuickHull' {
  declare module.exports: any;
}

declare module 'quickhull3d/dist/Vertex' {
  declare module.exports: any;
}

declare module 'quickhull3d/dist/VertexList' {
  declare module.exports: any;
}

// Filename aliases
declare module 'quickhull3d/dist/Face.js' {
  declare module.exports: $Exports<'quickhull3d/dist/Face'>;
}
declare module 'quickhull3d/dist/HalfEdge.js' {
  declare module.exports: $Exports<'quickhull3d/dist/HalfEdge'>;
}
declare module 'quickhull3d/dist/index' {
  declare module.exports: $Exports<'quickhull3d/dist'>;
}
declare module 'quickhull3d/dist/index.js' {
  declare module.exports: $Exports<'quickhull3d/dist'>;
}
declare module 'quickhull3d/dist/QuickHull.js' {
  declare module.exports: $Exports<'quickhull3d/dist/QuickHull'>;
}
declare module 'quickhull3d/dist/Vertex.js' {
  declare module.exports: $Exports<'quickhull3d/dist/Vertex'>;
}
declare module 'quickhull3d/dist/VertexList.js' {
  declare module.exports: $Exports<'quickhull3d/dist/VertexList'>;
}
