// flow-typed signature: f794a4909b1ce71d9d28f256793c934d
// flow-typed version: <<STUB>>/react-app-rewired_v^1.6.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewired'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewired' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-app-rewired/bin/index' {
  declare module.exports: any;
}

declare module 'react-app-rewired/bin/jest' {
  declare module.exports: any;
}

declare module 'react-app-rewired/config-overrides' {
  declare module.exports: any;
}

declare module 'react-app-rewired/examples/configurable-overrides/custom-overides/index' {
  declare module.exports: any;
}

declare module 'react-app-rewired/examples/configurable-overrides/src/index' {
  declare module.exports: any;
}

declare module 'react-app-rewired/scripts/build' {
  declare module.exports: any;
}

declare module 'react-app-rewired/scripts/start' {
  declare module.exports: any;
}

declare module 'react-app-rewired/scripts/test' {
  declare module.exports: any;
}

declare module 'react-app-rewired/scripts/utils/babelTransform' {
  declare module.exports: any;
}

declare module 'react-app-rewired/scripts/utils/paths' {
  declare module.exports: any;
}

declare module 'react-app-rewired/scripts/utils/rewireJestConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-app-rewired/bin/index.js' {
  declare module.exports: $Exports<'react-app-rewired/bin/index'>;
}
declare module 'react-app-rewired/bin/jest.js' {
  declare module.exports: $Exports<'react-app-rewired/bin/jest'>;
}
declare module 'react-app-rewired/config-overrides.js' {
  declare module.exports: $Exports<'react-app-rewired/config-overrides'>;
}
declare module 'react-app-rewired/examples/configurable-overrides/custom-overides/index.js' {
  declare module.exports: $Exports<'react-app-rewired/examples/configurable-overrides/custom-overides/index'>;
}
declare module 'react-app-rewired/examples/configurable-overrides/src/index.js' {
  declare module.exports: $Exports<'react-app-rewired/examples/configurable-overrides/src/index'>;
}
declare module 'react-app-rewired/index' {
  declare module.exports: $Exports<'react-app-rewired'>;
}
declare module 'react-app-rewired/index.js' {
  declare module.exports: $Exports<'react-app-rewired'>;
}
declare module 'react-app-rewired/scripts/build.js' {
  declare module.exports: $Exports<'react-app-rewired/scripts/build'>;
}
declare module 'react-app-rewired/scripts/start.js' {
  declare module.exports: $Exports<'react-app-rewired/scripts/start'>;
}
declare module 'react-app-rewired/scripts/test.js' {
  declare module.exports: $Exports<'react-app-rewired/scripts/test'>;
}
declare module 'react-app-rewired/scripts/utils/babelTransform.js' {
  declare module.exports: $Exports<'react-app-rewired/scripts/utils/babelTransform'>;
}
declare module 'react-app-rewired/scripts/utils/paths.js' {
  declare module.exports: $Exports<'react-app-rewired/scripts/utils/paths'>;
}
declare module 'react-app-rewired/scripts/utils/rewireJestConfig.js' {
  declare module.exports: $Exports<'react-app-rewired/scripts/utils/rewireJestConfig'>;
}
