// flow-typed signature: 982702443fea9ef8f3d7ccbabae19b34
// flow-typed version: <<STUB>>/react-hover-observer_v^2.1.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hover-observer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hover-observer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hover-observer/dist/es/ReactHoverObserver' {
  declare module.exports: any;
}

declare module 'react-hover-observer/dist/es/utils/noop' {
  declare module.exports: any;
}

declare module 'react-hover-observer/dist/ReactHoverObserver' {
  declare module.exports: any;
}

declare module 'react-hover-observer/dist/umd/ReactHoverObserver' {
  declare module.exports: any;
}

declare module 'react-hover-observer/dist/utils/noop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hover-observer/dist/es/ReactHoverObserver.js' {
  declare module.exports: $Exports<'react-hover-observer/dist/es/ReactHoverObserver'>;
}
declare module 'react-hover-observer/dist/es/utils/noop.js' {
  declare module.exports: $Exports<'react-hover-observer/dist/es/utils/noop'>;
}
declare module 'react-hover-observer/dist/ReactHoverObserver.js' {
  declare module.exports: $Exports<'react-hover-observer/dist/ReactHoverObserver'>;
}
declare module 'react-hover-observer/dist/umd/ReactHoverObserver.js' {
  declare module.exports: $Exports<'react-hover-observer/dist/umd/ReactHoverObserver'>;
}
declare module 'react-hover-observer/dist/utils/noop.js' {
  declare module.exports: $Exports<'react-hover-observer/dist/utils/noop'>;
}
