// flow-typed signature: ecb1403ef67d75c4404dbb12bc459143
// flow-typed version: <<STUB>>/react-document-events_v1.4.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-document-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-document-events' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-document-events/build/events' {
  declare module.exports: any;
}

declare module 'react-document-events/build/ReactDocumentEvents' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-document-events/build/events.js' {
  declare module.exports: $Exports<'react-document-events/build/events'>;
}
declare module 'react-document-events/build/ReactDocumentEvents.js' {
  declare module.exports: $Exports<'react-document-events/build/ReactDocumentEvents'>;
}
declare module 'react-document-events/index' {
  declare module.exports: $Exports<'react-document-events'>;
}
declare module 'react-document-events/index.js' {
  declare module.exports: $Exports<'react-document-events'>;
}
