// flow-typed signature: 4735e4bdcec7383a360a38defd67ebde
// flow-typed version: <<STUB>>/react-container-dimensions_v1.4.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-container-dimensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-container-dimensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-container-dimensions/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-container-dimensions/lib/index.js' {
  declare module.exports: $Exports<'react-container-dimensions/lib/index'>;
}
