// flow-typed signature: 3d2c742f46861f761f4f80c97ec397a5
// flow-typed version: <<STUB>>/react-chartjs-2_v2.7.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-chartjs-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-chartjs-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-chartjs-2/dist/react-chartjs-2' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/dist/react-chartjs-2.min' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/es/index' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/gulpfile' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/lib/index' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/stories/index' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/stories/MixLineBar' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/stories/StockExamples' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/stories/UpdatingChart' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/stories/Welcome' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/test/__tests__/Chart_spec' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/test/config/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-chartjs-2/dist/react-chartjs-2.js' {
  declare module.exports: $Exports<'react-chartjs-2/dist/react-chartjs-2'>;
}
declare module 'react-chartjs-2/dist/react-chartjs-2.min.js' {
  declare module.exports: $Exports<'react-chartjs-2/dist/react-chartjs-2.min'>;
}
declare module 'react-chartjs-2/es/index.js' {
  declare module.exports: $Exports<'react-chartjs-2/es/index'>;
}
declare module 'react-chartjs-2/gulpfile.js' {
  declare module.exports: $Exports<'react-chartjs-2/gulpfile'>;
}
declare module 'react-chartjs-2/lib/index.js' {
  declare module.exports: $Exports<'react-chartjs-2/lib/index'>;
}
declare module 'react-chartjs-2/stories/index.js' {
  declare module.exports: $Exports<'react-chartjs-2/stories/index'>;
}
declare module 'react-chartjs-2/stories/MixLineBar.js' {
  declare module.exports: $Exports<'react-chartjs-2/stories/MixLineBar'>;
}
declare module 'react-chartjs-2/stories/StockExamples.js' {
  declare module.exports: $Exports<'react-chartjs-2/stories/StockExamples'>;
}
declare module 'react-chartjs-2/stories/UpdatingChart.js' {
  declare module.exports: $Exports<'react-chartjs-2/stories/UpdatingChart'>;
}
declare module 'react-chartjs-2/stories/Welcome.js' {
  declare module.exports: $Exports<'react-chartjs-2/stories/Welcome'>;
}
declare module 'react-chartjs-2/test/__tests__/Chart_spec.js' {
  declare module.exports: $Exports<'react-chartjs-2/test/__tests__/Chart_spec'>;
}
declare module 'react-chartjs-2/test/config/setup.js' {
  declare module.exports: $Exports<'react-chartjs-2/test/config/setup'>;
}
