// flow-typed signature: 353dbfd72d1661eef30d1ebf3b4181a8
// flow-typed version: <<STUB>>/react-select_v1.2.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-select/dist/react-select.es' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.min' {
  declare module.exports: any;
}

declare module 'react-select/lib/Async' {
  declare module.exports: any;
}

declare module 'react-select/lib/AsyncCreatable' {
  declare module.exports: any;
}

declare module 'react-select/lib/Creatable' {
  declare module.exports: any;
}

declare module 'react-select/lib/index' {
  declare module.exports: any;
}

declare module 'react-select/lib/Option' {
  declare module.exports: any;
}

declare module 'react-select/lib/Select' {
  declare module.exports: any;
}

declare module 'react-select/lib/utils/blockEvent' {
  declare module.exports: any;
}

declare module 'react-select/lib/utils/defaultArrowRenderer' {
  declare module.exports: any;
}

declare module 'react-select/lib/utils/defaultClearRenderer' {
  declare module.exports: any;
}

declare module 'react-select/lib/utils/defaultFilterOptions' {
  declare module.exports: any;
}

declare module 'react-select/lib/utils/defaultMenuRenderer' {
  declare module.exports: any;
}

declare module 'react-select/lib/utils/stripDiacritics' {
  declare module.exports: any;
}

declare module 'react-select/lib/utils/trim' {
  declare module.exports: any;
}

declare module 'react-select/lib/Value' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-select/dist/react-select.es.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.es'>;
}
declare module 'react-select/dist/react-select.js' {
  declare module.exports: $Exports<'react-select/dist/react-select'>;
}
declare module 'react-select/dist/react-select.min.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.min'>;
}
declare module 'react-select/lib/Async.js' {
  declare module.exports: $Exports<'react-select/lib/Async'>;
}
declare module 'react-select/lib/AsyncCreatable.js' {
  declare module.exports: $Exports<'react-select/lib/AsyncCreatable'>;
}
declare module 'react-select/lib/Creatable.js' {
  declare module.exports: $Exports<'react-select/lib/Creatable'>;
}
declare module 'react-select/lib/index.js' {
  declare module.exports: $Exports<'react-select/lib/index'>;
}
declare module 'react-select/lib/Option.js' {
  declare module.exports: $Exports<'react-select/lib/Option'>;
}
declare module 'react-select/lib/Select.js' {
  declare module.exports: $Exports<'react-select/lib/Select'>;
}
declare module 'react-select/lib/utils/blockEvent.js' {
  declare module.exports: $Exports<'react-select/lib/utils/blockEvent'>;
}
declare module 'react-select/lib/utils/defaultArrowRenderer.js' {
  declare module.exports: $Exports<'react-select/lib/utils/defaultArrowRenderer'>;
}
declare module 'react-select/lib/utils/defaultClearRenderer.js' {
  declare module.exports: $Exports<'react-select/lib/utils/defaultClearRenderer'>;
}
declare module 'react-select/lib/utils/defaultFilterOptions.js' {
  declare module.exports: $Exports<'react-select/lib/utils/defaultFilterOptions'>;
}
declare module 'react-select/lib/utils/defaultMenuRenderer.js' {
  declare module.exports: $Exports<'react-select/lib/utils/defaultMenuRenderer'>;
}
declare module 'react-select/lib/utils/stripDiacritics.js' {
  declare module.exports: $Exports<'react-select/lib/utils/stripDiacritics'>;
}
declare module 'react-select/lib/utils/trim.js' {
  declare module.exports: $Exports<'react-select/lib/utils/trim'>;
}
declare module 'react-select/lib/Value.js' {
  declare module.exports: $Exports<'react-select/lib/Value'>;
}
