// flow-typed signature: fc9f7def9e63fe9c1fdf818124f3bef2
// flow-typed version: <<STUB>>/react-autocomplete_vjanpaul123/react-autocomplete#bc8737070b5744069719c8fcd4e0a197192b0d48/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-autocomplete'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-autocomplete' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-autocomplete/bin/generate-api-doc' {
  declare module.exports: any;
}

declare module 'react-autocomplete/bin/generate-readme' {
  declare module.exports: any;
}

declare module 'react-autocomplete/build/lib/Autocomplete' {
  declare module.exports: any;
}

declare module 'react-autocomplete/build/lib/index' {
  declare module.exports: any;
}

declare module 'react-autocomplete/examples/async-data/app' {
  declare module.exports: any;
}

declare module 'react-autocomplete/examples/custom-menu/app' {
  declare module.exports: any;
}

declare module 'react-autocomplete/examples/managed-menu-visibility/app' {
  declare module.exports: any;
}

declare module 'react-autocomplete/examples/static-data/app' {
  declare module.exports: any;
}

declare module 'react-autocomplete/lib/__tests__/Autocomplete-test' {
  declare module.exports: any;
}

declare module 'react-autocomplete/lib/Autocomplete' {
  declare module.exports: any;
}

declare module 'react-autocomplete/lib/index' {
  declare module.exports: any;
}

declare module 'react-autocomplete/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-autocomplete/bin/generate-api-doc.js' {
  declare module.exports: $Exports<'react-autocomplete/bin/generate-api-doc'>;
}
declare module 'react-autocomplete/bin/generate-readme.js' {
  declare module.exports: $Exports<'react-autocomplete/bin/generate-readme'>;
}
declare module 'react-autocomplete/build/lib/Autocomplete.js' {
  declare module.exports: $Exports<'react-autocomplete/build/lib/Autocomplete'>;
}
declare module 'react-autocomplete/build/lib/index.js' {
  declare module.exports: $Exports<'react-autocomplete/build/lib/index'>;
}
declare module 'react-autocomplete/examples/async-data/app.js' {
  declare module.exports: $Exports<'react-autocomplete/examples/async-data/app'>;
}
declare module 'react-autocomplete/examples/custom-menu/app.js' {
  declare module.exports: $Exports<'react-autocomplete/examples/custom-menu/app'>;
}
declare module 'react-autocomplete/examples/managed-menu-visibility/app.js' {
  declare module.exports: $Exports<'react-autocomplete/examples/managed-menu-visibility/app'>;
}
declare module 'react-autocomplete/examples/static-data/app.js' {
  declare module.exports: $Exports<'react-autocomplete/examples/static-data/app'>;
}
declare module 'react-autocomplete/lib/__tests__/Autocomplete-test.js' {
  declare module.exports: $Exports<'react-autocomplete/lib/__tests__/Autocomplete-test'>;
}
declare module 'react-autocomplete/lib/Autocomplete.js' {
  declare module.exports: $Exports<'react-autocomplete/lib/Autocomplete'>;
}
declare module 'react-autocomplete/lib/index.js' {
  declare module.exports: $Exports<'react-autocomplete/lib/index'>;
}
declare module 'react-autocomplete/lib/utils.js' {
  declare module.exports: $Exports<'react-autocomplete/lib/utils'>;
}
