// flow-typed signature: 3be3175cf5e12982a34e8497e57c1a37
// flow-typed version: <<STUB>>/react-json-tree_v0.11.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-json-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-json-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-json-tree/lib/createStylingFromTheme' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/getCollectionEntries' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/index' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/ItemRange' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/JSONArrayNode' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/JSONArrow' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/JSONIterableNode' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/JSONNestedNode' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/JSONNode' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/JSONObjectNode' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/JSONValueNode' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/objType' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/themes/solarized' {
  declare module.exports: any;
}

declare module 'react-json-tree/lib/utils/hexToRgb' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-json-tree/lib/createStylingFromTheme.js' {
  declare module.exports: $Exports<'react-json-tree/lib/createStylingFromTheme'>;
}
declare module 'react-json-tree/lib/getCollectionEntries.js' {
  declare module.exports: $Exports<'react-json-tree/lib/getCollectionEntries'>;
}
declare module 'react-json-tree/lib/index.js' {
  declare module.exports: $Exports<'react-json-tree/lib/index'>;
}
declare module 'react-json-tree/lib/ItemRange.js' {
  declare module.exports: $Exports<'react-json-tree/lib/ItemRange'>;
}
declare module 'react-json-tree/lib/JSONArrayNode.js' {
  declare module.exports: $Exports<'react-json-tree/lib/JSONArrayNode'>;
}
declare module 'react-json-tree/lib/JSONArrow.js' {
  declare module.exports: $Exports<'react-json-tree/lib/JSONArrow'>;
}
declare module 'react-json-tree/lib/JSONIterableNode.js' {
  declare module.exports: $Exports<'react-json-tree/lib/JSONIterableNode'>;
}
declare module 'react-json-tree/lib/JSONNestedNode.js' {
  declare module.exports: $Exports<'react-json-tree/lib/JSONNestedNode'>;
}
declare module 'react-json-tree/lib/JSONNode.js' {
  declare module.exports: $Exports<'react-json-tree/lib/JSONNode'>;
}
declare module 'react-json-tree/lib/JSONObjectNode.js' {
  declare module.exports: $Exports<'react-json-tree/lib/JSONObjectNode'>;
}
declare module 'react-json-tree/lib/JSONValueNode.js' {
  declare module.exports: $Exports<'react-json-tree/lib/JSONValueNode'>;
}
declare module 'react-json-tree/lib/objType.js' {
  declare module.exports: $Exports<'react-json-tree/lib/objType'>;
}
declare module 'react-json-tree/lib/themes/solarized.js' {
  declare module.exports: $Exports<'react-json-tree/lib/themes/solarized'>;
}
declare module 'react-json-tree/lib/utils/hexToRgb.js' {
  declare module.exports: $Exports<'react-json-tree/lib/utils/hexToRgb'>;
}
