// flow-typed signature: b8600077500c38f2c741f41f3d66ea47
// flow-typed version: <<STUB>>/react-container-dimensions_v1.3.3/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-container-dimensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-container-dimensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-container-dimensions/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-container-dimensions/lib/index.js' {
  declare module.exports: $Exports<'react-container-dimensions/lib/index'>;
}
