// flow-typed signature: b4de32e8e262a2dee67be1edbdc86780
// flow-typed version: <<STUB>>/react-svg-loader_v^2.1.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg-loader/lib/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg-loader/lib/loader.js' {
  declare module.exports: $Exports<'react-svg-loader/lib/loader'>;
}
