// flow-typed signature: 03de5f508850eb64b18b656b4319f2c3
// flow-typed version: <<STUB>>/react-hooks-testing-library_v^0.4.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hooks-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hooks-testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hooks-testing-library/cleanup-after-each' {
  declare module.exports: any;
}

declare module 'react-hooks-testing-library/lib' {
  declare module.exports: any;
}

declare module 'react-hooks-testing-library/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hooks-testing-library/cleanup-after-each.js' {
  declare module.exports: $Exports<'react-hooks-testing-library/cleanup-after-each'>;
}
declare module 'react-hooks-testing-library/lib/index' {
  declare module.exports: $Exports<'react-hooks-testing-library/lib'>;
}
declare module 'react-hooks-testing-library/lib/index.js' {
  declare module.exports: $Exports<'react-hooks-testing-library/lib'>;
}
declare module 'react-hooks-testing-library/src/index' {
  declare module.exports: $Exports<'react-hooks-testing-library/src'>;
}
declare module 'react-hooks-testing-library/src/index.js' {
  declare module.exports: $Exports<'react-hooks-testing-library/src'>;
}
