// flow-typed signature: 976325ae5b636717254942015ec1ffa9
// flow-typed version: <<STUB>>/react-virtualized-select_v^3.1.3/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-virtualized-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-virtualized-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-virtualized-select/dist/commonjs' {
  declare module.exports: any;
}

declare module 'react-virtualized-select/dist/commonjs/TestUtils' {
  declare module.exports: any;
}

declare module 'react-virtualized-select/dist/commonjs/VirtualizedSelect' {
  declare module.exports: any;
}

declare module 'react-virtualized-select/dist/commonjs/VirtualizedSelect/VirtualizedSelect' {
  declare module.exports: any;
}

declare module 'react-virtualized-select/dist/es' {
  declare module.exports: any;
}

declare module 'react-virtualized-select/dist/es/TestUtils' {
  declare module.exports: any;
}

declare module 'react-virtualized-select/dist/es/VirtualizedSelect' {
  declare module.exports: any;
}

declare module 'react-virtualized-select/dist/es/VirtualizedSelect/VirtualizedSelect' {
  declare module.exports: any;
}

declare module 'react-virtualized-select/dist/umd/react-virtualized-select' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-virtualized-select/dist/commonjs/index' {
  declare module.exports: $Exports<'react-virtualized-select/dist/commonjs'>;
}
declare module 'react-virtualized-select/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-virtualized-select/dist/commonjs'>;
}
declare module 'react-virtualized-select/dist/commonjs/TestUtils.js' {
  declare module.exports: $Exports<'react-virtualized-select/dist/commonjs/TestUtils'>;
}
declare module 'react-virtualized-select/dist/commonjs/VirtualizedSelect/index' {
  declare module.exports: $Exports<'react-virtualized-select/dist/commonjs/VirtualizedSelect'>;
}
declare module 'react-virtualized-select/dist/commonjs/VirtualizedSelect/index.js' {
  declare module.exports: $Exports<'react-virtualized-select/dist/commonjs/VirtualizedSelect'>;
}
declare module 'react-virtualized-select/dist/commonjs/VirtualizedSelect/VirtualizedSelect.js' {
  declare module.exports: $Exports<'react-virtualized-select/dist/commonjs/VirtualizedSelect/VirtualizedSelect'>;
}
declare module 'react-virtualized-select/dist/es/index' {
  declare module.exports: $Exports<'react-virtualized-select/dist/es'>;
}
declare module 'react-virtualized-select/dist/es/index.js' {
  declare module.exports: $Exports<'react-virtualized-select/dist/es'>;
}
declare module 'react-virtualized-select/dist/es/TestUtils.js' {
  declare module.exports: $Exports<'react-virtualized-select/dist/es/TestUtils'>;
}
declare module 'react-virtualized-select/dist/es/VirtualizedSelect/index' {
  declare module.exports: $Exports<'react-virtualized-select/dist/es/VirtualizedSelect'>;
}
declare module 'react-virtualized-select/dist/es/VirtualizedSelect/index.js' {
  declare module.exports: $Exports<'react-virtualized-select/dist/es/VirtualizedSelect'>;
}
declare module 'react-virtualized-select/dist/es/VirtualizedSelect/VirtualizedSelect.js' {
  declare module.exports: $Exports<'react-virtualized-select/dist/es/VirtualizedSelect/VirtualizedSelect'>;
}
declare module 'react-virtualized-select/dist/umd/react-virtualized-select.js' {
  declare module.exports: $Exports<'react-virtualized-select/dist/umd/react-virtualized-select'>;
}
