// flow-typed signature: 93a2d7d837fc0aed339ff9d3405454e0
// flow-typed version: <<STUB>>/reg-simple-keygen-plugin_v0.7.16/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reg-simple-keygen-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reg-simple-keygen-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reg-simple-keygen-plugin/lib' {
  declare module.exports: any;
}

declare module 'reg-simple-keygen-plugin/lib/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reg-simple-keygen-plugin/lib/index' {
  declare module.exports: $Exports<'reg-simple-keygen-plugin/lib'>;
}
declare module 'reg-simple-keygen-plugin/lib/index.js' {
  declare module.exports: $Exports<'reg-simple-keygen-plugin/lib'>;
}
declare module 'reg-simple-keygen-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'reg-simple-keygen-plugin/lib/plugin'>;
}
