// flow-typed signature: f16796c75a0304889cf5a5c24924aae2
// flow-typed version: <<STUB>>/reg-suit_v0.7.17/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reg-suit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reg-suit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reg-suit/lib/cli-options' {
  declare module.exports: any;
}

declare module 'reg-suit/lib/cli' {
  declare module.exports: any;
}

declare module 'reg-suit/lib/commands/compare' {
  declare module.exports: any;
}

declare module 'reg-suit/lib/commands/init' {
  declare module.exports: any;
}

declare module 'reg-suit/lib/commands/install' {
  declare module.exports: any;
}

declare module 'reg-suit/lib/commands/prepare' {
  declare module.exports: any;
}

declare module 'reg-suit/lib/commands/publish' {
  declare module.exports: any;
}

declare module 'reg-suit/lib/commands/run' {
  declare module.exports: any;
}

declare module 'reg-suit/lib/commands/sync-expected' {
  declare module.exports: any;
}

declare module 'reg-suit/lib/get-reg-core' {
  declare module.exports: any;
}

declare module 'reg-suit/lib/package-util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reg-suit/lib/cli-options.js' {
  declare module.exports: $Exports<'reg-suit/lib/cli-options'>;
}
declare module 'reg-suit/lib/cli.js' {
  declare module.exports: $Exports<'reg-suit/lib/cli'>;
}
declare module 'reg-suit/lib/commands/compare.js' {
  declare module.exports: $Exports<'reg-suit/lib/commands/compare'>;
}
declare module 'reg-suit/lib/commands/init.js' {
  declare module.exports: $Exports<'reg-suit/lib/commands/init'>;
}
declare module 'reg-suit/lib/commands/install.js' {
  declare module.exports: $Exports<'reg-suit/lib/commands/install'>;
}
declare module 'reg-suit/lib/commands/prepare.js' {
  declare module.exports: $Exports<'reg-suit/lib/commands/prepare'>;
}
declare module 'reg-suit/lib/commands/publish.js' {
  declare module.exports: $Exports<'reg-suit/lib/commands/publish'>;
}
declare module 'reg-suit/lib/commands/run.js' {
  declare module.exports: $Exports<'reg-suit/lib/commands/run'>;
}
declare module 'reg-suit/lib/commands/sync-expected.js' {
  declare module.exports: $Exports<'reg-suit/lib/commands/sync-expected'>;
}
declare module 'reg-suit/lib/get-reg-core.js' {
  declare module.exports: $Exports<'reg-suit/lib/get-reg-core'>;
}
declare module 'reg-suit/lib/package-util.js' {
  declare module.exports: $Exports<'reg-suit/lib/package-util'>;
}
