// flow-typed signature: c4b0e56b0986d0d462e4f7d0cd898014
// flow-typed version: <<STUB>>/regl_v^1.3.1/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'regl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'regl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'regl/browserify/transform' {
  declare module.exports: any;
}

declare module 'regl/dist/regl' {
  declare module.exports: any;
}

declare module 'regl/dist/regl.min' {
  declare module.exports: any;
}

declare module 'regl/dist/regl.unchecked' {
  declare module.exports: any;
}

declare module 'regl/lib/attribute' {
  declare module.exports: any;
}

declare module 'regl/lib/buffer' {
  declare module.exports: any;
}

declare module 'regl/lib/core' {
  declare module.exports: any;
}

declare module 'regl/lib/dynamic' {
  declare module.exports: any;
}

declare module 'regl/lib/elements' {
  declare module.exports: any;
}

declare module 'regl/lib/extension' {
  declare module.exports: any;
}

declare module 'regl/lib/framebuffer' {
  declare module.exports: any;
}

declare module 'regl/lib/limits' {
  declare module.exports: any;
}

declare module 'regl/lib/read' {
  declare module.exports: any;
}

declare module 'regl/lib/renderbuffer' {
  declare module.exports: any;
}

declare module 'regl/lib/shader' {
  declare module.exports: any;
}

declare module 'regl/lib/stats' {
  declare module.exports: any;
}

declare module 'regl/lib/strings' {
  declare module.exports: any;
}

declare module 'regl/lib/texture' {
  declare module.exports: any;
}

declare module 'regl/lib/timer' {
  declare module.exports: any;
}

declare module 'regl/lib/util/check' {
  declare module.exports: any;
}

declare module 'regl/lib/util/clock' {
  declare module.exports: any;
}

declare module 'regl/lib/util/codegen' {
  declare module.exports: any;
}

declare module 'regl/lib/util/extend' {
  declare module.exports: any;
}

declare module 'regl/lib/util/flatten' {
  declare module.exports: any;
}

declare module 'regl/lib/util/is-array-like' {
  declare module.exports: any;
}

declare module 'regl/lib/util/is-ndarray' {
  declare module.exports: any;
}

declare module 'regl/lib/util/is-pow2' {
  declare module.exports: any;
}

declare module 'regl/lib/util/is-typed-array' {
  declare module.exports: any;
}

declare module 'regl/lib/util/loop' {
  declare module.exports: any;
}

declare module 'regl/lib/util/pool' {
  declare module.exports: any;
}

declare module 'regl/lib/util/raf' {
  declare module.exports: any;
}

declare module 'regl/lib/util/to-half-float' {
  declare module.exports: any;
}

declare module 'regl/lib/util/values' {
  declare module.exports: any;
}

declare module 'regl/lib/webgl' {
  declare module.exports: any;
}

declare module 'regl/regl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'regl/browserify/transform.js' {
  declare module.exports: $Exports<'regl/browserify/transform'>;
}
declare module 'regl/dist/regl.js' {
  declare module.exports: $Exports<'regl/dist/regl'>;
}
declare module 'regl/dist/regl.min.js' {
  declare module.exports: $Exports<'regl/dist/regl.min'>;
}
declare module 'regl/dist/regl.unchecked.js' {
  declare module.exports: $Exports<'regl/dist/regl.unchecked'>;
}
declare module 'regl/lib/attribute.js' {
  declare module.exports: $Exports<'regl/lib/attribute'>;
}
declare module 'regl/lib/buffer.js' {
  declare module.exports: $Exports<'regl/lib/buffer'>;
}
declare module 'regl/lib/core.js' {
  declare module.exports: $Exports<'regl/lib/core'>;
}
declare module 'regl/lib/dynamic.js' {
  declare module.exports: $Exports<'regl/lib/dynamic'>;
}
declare module 'regl/lib/elements.js' {
  declare module.exports: $Exports<'regl/lib/elements'>;
}
declare module 'regl/lib/extension.js' {
  declare module.exports: $Exports<'regl/lib/extension'>;
}
declare module 'regl/lib/framebuffer.js' {
  declare module.exports: $Exports<'regl/lib/framebuffer'>;
}
declare module 'regl/lib/limits.js' {
  declare module.exports: $Exports<'regl/lib/limits'>;
}
declare module 'regl/lib/read.js' {
  declare module.exports: $Exports<'regl/lib/read'>;
}
declare module 'regl/lib/renderbuffer.js' {
  declare module.exports: $Exports<'regl/lib/renderbuffer'>;
}
declare module 'regl/lib/shader.js' {
  declare module.exports: $Exports<'regl/lib/shader'>;
}
declare module 'regl/lib/stats.js' {
  declare module.exports: $Exports<'regl/lib/stats'>;
}
declare module 'regl/lib/strings.js' {
  declare module.exports: $Exports<'regl/lib/strings'>;
}
declare module 'regl/lib/texture.js' {
  declare module.exports: $Exports<'regl/lib/texture'>;
}
declare module 'regl/lib/timer.js' {
  declare module.exports: $Exports<'regl/lib/timer'>;
}
declare module 'regl/lib/util/check.js' {
  declare module.exports: $Exports<'regl/lib/util/check'>;
}
declare module 'regl/lib/util/clock.js' {
  declare module.exports: $Exports<'regl/lib/util/clock'>;
}
declare module 'regl/lib/util/codegen.js' {
  declare module.exports: $Exports<'regl/lib/util/codegen'>;
}
declare module 'regl/lib/util/extend.js' {
  declare module.exports: $Exports<'regl/lib/util/extend'>;
}
declare module 'regl/lib/util/flatten.js' {
  declare module.exports: $Exports<'regl/lib/util/flatten'>;
}
declare module 'regl/lib/util/is-array-like.js' {
  declare module.exports: $Exports<'regl/lib/util/is-array-like'>;
}
declare module 'regl/lib/util/is-ndarray.js' {
  declare module.exports: $Exports<'regl/lib/util/is-ndarray'>;
}
declare module 'regl/lib/util/is-pow2.js' {
  declare module.exports: $Exports<'regl/lib/util/is-pow2'>;
}
declare module 'regl/lib/util/is-typed-array.js' {
  declare module.exports: $Exports<'regl/lib/util/is-typed-array'>;
}
declare module 'regl/lib/util/loop.js' {
  declare module.exports: $Exports<'regl/lib/util/loop'>;
}
declare module 'regl/lib/util/pool.js' {
  declare module.exports: $Exports<'regl/lib/util/pool'>;
}
declare module 'regl/lib/util/raf.js' {
  declare module.exports: $Exports<'regl/lib/util/raf'>;
}
declare module 'regl/lib/util/to-half-float.js' {
  declare module.exports: $Exports<'regl/lib/util/to-half-float'>;
}
declare module 'regl/lib/util/values.js' {
  declare module.exports: $Exports<'regl/lib/util/values'>;
}
declare module 'regl/lib/webgl.js' {
  declare module.exports: $Exports<'regl/lib/webgl'>;
}
declare module 'regl/regl.js' {
  declare module.exports: $Exports<'regl/regl'>;
}
