// flow-typed signature: f044410d90868ab0297b7db6d5db5a8c
// flow-typed version: <<STUB>>/retext-smartypants_v^3.0.2/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-smartypants'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-smartypants' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-smartypants/index' {
  declare module.exports: $Exports<'retext-smartypants'>;
}
declare module 'retext-smartypants/index.js' {
  declare module.exports: $Exports<'retext-smartypants'>;
}
