// flow-typed signature: a823c33c15fe6a2e534f18769f898ec6
// flow-typed version: <<STUB>>/retext_v^6.0.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext/index' {
  declare module.exports: $Exports<'retext'>;
}
declare module 'retext/index.js' {
  declare module.exports: $Exports<'retext'>;
}
