// flow-typed signature: c37d133cbf63d9bfb4c32fa40cad1e4c
// flow-typed version: <<STUB>>/rollup-plugin-filesize_v^5.0.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-filesize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-filesize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-filesize/dist/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-filesize/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-filesize/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-filesize/dist/index'>;
}
declare module 'rollup-plugin-filesize/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-filesize/src/index'>;
}
