// flow-typed signature: d5bdcb6b32f0dfcecd27ec8dab0d86b8
// flow-typed version: <<STUB>>/rollup-plugin-copy_v^0.2.3/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-copy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-copy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-plugin-copy/index' {
  declare module.exports: $Exports<'rollup-plugin-copy'>;
}
declare module 'rollup-plugin-copy/index.js' {
  declare module.exports: $Exports<'rollup-plugin-copy'>;
}
