// flow-typed signature: c13e7fc71eff2e6a776b38920676f9ed
// flow-typed version: <<STUB>>/rollup-plugin-peer-deps-external_v^2.2.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-peer-deps-external'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-peer-deps-external' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-peer-deps-external/dist/rollup-plugin-peer-deps-external' {
  declare module.exports: any;
}

declare module 'rollup-plugin-peer-deps-external/dist/rollup-plugin-peer-deps-external.module' {
  declare module.exports: any;
}

declare module 'rollup-plugin-peer-deps-external/src/external-to-fn' {
  declare module.exports: any;
}

declare module 'rollup-plugin-peer-deps-external/src/external-to-fn.spec' {
  declare module.exports: any;
}

declare module 'rollup-plugin-peer-deps-external/src/get-deps' {
  declare module.exports: any;
}

declare module 'rollup-plugin-peer-deps-external/src/get-modules-matcher' {
  declare module.exports: any;
}

declare module 'rollup-plugin-peer-deps-external/src/get-modules-matcher.spec' {
  declare module.exports: any;
}

declare module 'rollup-plugin-peer-deps-external/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-peer-deps-external/dist/rollup-plugin-peer-deps-external.js' {
  declare module.exports: $Exports<'rollup-plugin-peer-deps-external/dist/rollup-plugin-peer-deps-external'>;
}
declare module 'rollup-plugin-peer-deps-external/dist/rollup-plugin-peer-deps-external.module.js' {
  declare module.exports: $Exports<'rollup-plugin-peer-deps-external/dist/rollup-plugin-peer-deps-external.module'>;
}
declare module 'rollup-plugin-peer-deps-external/src/external-to-fn.js' {
  declare module.exports: $Exports<'rollup-plugin-peer-deps-external/src/external-to-fn'>;
}
declare module 'rollup-plugin-peer-deps-external/src/external-to-fn.spec.js' {
  declare module.exports: $Exports<'rollup-plugin-peer-deps-external/src/external-to-fn.spec'>;
}
declare module 'rollup-plugin-peer-deps-external/src/get-deps.js' {
  declare module.exports: $Exports<'rollup-plugin-peer-deps-external/src/get-deps'>;
}
declare module 'rollup-plugin-peer-deps-external/src/get-modules-matcher.js' {
  declare module.exports: $Exports<'rollup-plugin-peer-deps-external/src/get-modules-matcher'>;
}
declare module 'rollup-plugin-peer-deps-external/src/get-modules-matcher.spec.js' {
  declare module.exports: $Exports<'rollup-plugin-peer-deps-external/src/get-modules-matcher.spec'>;
}
declare module 'rollup-plugin-peer-deps-external/src/index' {
  declare module.exports: $Exports<'rollup-plugin-peer-deps-external/src'>;
}
declare module 'rollup-plugin-peer-deps-external/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-peer-deps-external/src'>;
}
