// flow-typed signature: 283e7341f20cbce789dd11ad3b475da0
// flow-typed version: <<STUB>>/rollup-plugin-local-resolve_v^1.0.7/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-local-resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-local-resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-local-resolve/dist/rollup-plugin-local-resolve.es2015' {
  declare module.exports: any;
}

declare module 'rollup-plugin-local-resolve/dist/rollup-plugin-local-resolve' {
  declare module.exports: any;
}

declare module 'rollup-plugin-local-resolve/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-local-resolve/dist/rollup-plugin-local-resolve.es2015.js' {
  declare module.exports: $Exports<'rollup-plugin-local-resolve/dist/rollup-plugin-local-resolve.es2015'>;
}
declare module 'rollup-plugin-local-resolve/dist/rollup-plugin-local-resolve.js' {
  declare module.exports: $Exports<'rollup-plugin-local-resolve/dist/rollup-plugin-local-resolve'>;
}
declare module 'rollup-plugin-local-resolve/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-local-resolve/src/index'>;
}
