// flow-typed signature: 11685bf293f698c2dd3057963366c97b
// flow-typed version: <<STUB>>/snappyjs_v0.6.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snappyjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snappyjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snappyjs/snappy_compressor' {
  declare module.exports: any;
}

declare module 'snappyjs/snappy_decompressor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snappyjs/index' {
  declare module.exports: $Exports<'snappyjs'>;
}
declare module 'snappyjs/index.js' {
  declare module.exports: $Exports<'snappyjs'>;
}
declare module 'snappyjs/snappy_compressor.js' {
  declare module.exports: $Exports<'snappyjs/snappy_compressor'>;
}
declare module 'snappyjs/snappy_decompressor.js' {
  declare module.exports: $Exports<'snappyjs/snappy_decompressor'>;
}
