// flow-typed signature: d50ab3640d0f12e8d0c4110f727ba59f
// flow-typed version: <<STUB>>/storybook-chrome-screenshot_v^1.4.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-chrome-screenshot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-chrome-screenshot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-chrome-screenshot/lib/__tests__/screenshot-options.test' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/cli' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/angular/initScreenshot' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/angular/models' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/angular/withScreenshot' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/noop/index' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/react/components/__tests__/InitScreenshotWrapper.test' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/react/components/__tests__/ScreenshotWrapper.test' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/react/components/InitScreenshotWrapper' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/react/components/ScreenshotWrapper' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/react/initScreenshot' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/react/withScreenshot' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/vue/hoc' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/vue/initScreenshot' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/vue/models' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/clients/vue/withScreenshot' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/__tests__/utils.test' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/__tests__/cli-options.mock' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/__tests__/Server.mock' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/__tests__/Server.test' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/__tests__/Terminal.mock' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/__tests__/Terminal.test' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/App' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/Browser' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/index' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/Page' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/Server' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/StoryStore' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/app/Terminal' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/client/__tests__/Env.test' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/client/AppAdapter' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/client/Client' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/client/Env' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/client/Gateway' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/client/index' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/constants' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/core/utils' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/index' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/initScreenshot' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/models/knobs' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/models/options' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/models/story' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/models/storybook' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/models/terminal' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/models/viewport' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/register' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/screenshot-options' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/lib/withScreenshot' {
  declare module.exports: any;
}

declare module 'storybook-chrome-screenshot/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-chrome-screenshot/lib/__tests__/screenshot-options.test.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/__tests__/screenshot-options.test'>;
}
declare module 'storybook-chrome-screenshot/lib/cli.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/cli'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/angular/initScreenshot.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/angular/initScreenshot'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/angular/models.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/angular/models'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/angular/withScreenshot.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/angular/withScreenshot'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/noop/index.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/noop/index'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/react/components/__tests__/InitScreenshotWrapper.test.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/react/components/__tests__/InitScreenshotWrapper.test'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/react/components/__tests__/ScreenshotWrapper.test.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/react/components/__tests__/ScreenshotWrapper.test'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/react/components/InitScreenshotWrapper.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/react/components/InitScreenshotWrapper'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/react/components/ScreenshotWrapper.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/react/components/ScreenshotWrapper'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/react/initScreenshot.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/react/initScreenshot'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/react/withScreenshot.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/react/withScreenshot'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/vue/hoc.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/vue/hoc'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/vue/initScreenshot.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/vue/initScreenshot'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/vue/models.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/vue/models'>;
}
declare module 'storybook-chrome-screenshot/lib/clients/vue/withScreenshot.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/clients/vue/withScreenshot'>;
}
declare module 'storybook-chrome-screenshot/lib/core/__tests__/utils.test.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/__tests__/utils.test'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/__tests__/cli-options.mock.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/__tests__/cli-options.mock'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/__tests__/Server.mock.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/__tests__/Server.mock'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/__tests__/Server.test.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/__tests__/Server.test'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/__tests__/Terminal.mock.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/__tests__/Terminal.mock'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/__tests__/Terminal.test.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/__tests__/Terminal.test'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/App.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/App'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/Browser.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/Browser'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/index.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/index'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/Page.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/Page'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/Server.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/Server'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/StoryStore.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/StoryStore'>;
}
declare module 'storybook-chrome-screenshot/lib/core/app/Terminal.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/app/Terminal'>;
}
declare module 'storybook-chrome-screenshot/lib/core/client/__tests__/Env.test.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/client/__tests__/Env.test'>;
}
declare module 'storybook-chrome-screenshot/lib/core/client/AppAdapter.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/client/AppAdapter'>;
}
declare module 'storybook-chrome-screenshot/lib/core/client/Client.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/client/Client'>;
}
declare module 'storybook-chrome-screenshot/lib/core/client/Env.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/client/Env'>;
}
declare module 'storybook-chrome-screenshot/lib/core/client/Gateway.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/client/Gateway'>;
}
declare module 'storybook-chrome-screenshot/lib/core/client/index.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/client/index'>;
}
declare module 'storybook-chrome-screenshot/lib/core/constants.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/constants'>;
}
declare module 'storybook-chrome-screenshot/lib/core/utils.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/core/utils'>;
}
declare module 'storybook-chrome-screenshot/lib/index.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/index'>;
}
declare module 'storybook-chrome-screenshot/lib/initScreenshot.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/initScreenshot'>;
}
declare module 'storybook-chrome-screenshot/lib/models/knobs.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/models/knobs'>;
}
declare module 'storybook-chrome-screenshot/lib/models/options.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/models/options'>;
}
declare module 'storybook-chrome-screenshot/lib/models/story.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/models/story'>;
}
declare module 'storybook-chrome-screenshot/lib/models/storybook.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/models/storybook'>;
}
declare module 'storybook-chrome-screenshot/lib/models/terminal.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/models/terminal'>;
}
declare module 'storybook-chrome-screenshot/lib/models/viewport.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/models/viewport'>;
}
declare module 'storybook-chrome-screenshot/lib/register.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/register'>;
}
declare module 'storybook-chrome-screenshot/lib/screenshot-options.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/screenshot-options'>;
}
declare module 'storybook-chrome-screenshot/lib/withScreenshot.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/lib/withScreenshot'>;
}
declare module 'storybook-chrome-screenshot/register.js' {
  declare module.exports: $Exports<'storybook-chrome-screenshot/register'>;
}
