// flow-typed signature: 9074debc552e5c728a107acb1b60fa25
// flow-typed version: <<STUB>>/storycap_v^2.3.5/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storycap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storycap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storycap/lib/client/is-screenshot' {
  declare module.exports: any;
}

declare module 'storycap/lib/client/register' {
  declare module.exports: any;
}

declare module 'storycap/lib/client/trigger-screenshot' {
  declare module.exports: any;
}

declare module 'storycap/lib/client/with-screenshot' {
  declare module.exports: any;
}

declare module 'storycap/lib' {
  declare module.exports: any;
}

declare module 'storycap/lib/node/capturing-browser' {
  declare module.exports: any;
}

declare module 'storycap/lib/node/cli' {
  declare module.exports: any;
}

declare module 'storycap/lib/node/errors' {
  declare module.exports: any;
}

declare module 'storycap/lib/node/file' {
  declare module.exports: any;
}

declare module 'storycap/lib/node/logger' {
  declare module.exports: any;
}

declare module 'storycap/lib/node/main' {
  declare module.exports: any;
}

declare module 'storycap/lib/node/screenshot-service' {
  declare module.exports: any;
}

declare module 'storycap/lib/node/types' {
  declare module.exports: any;
}

declare module 'storycap/lib/shared/screenshot-options-helper' {
  declare module.exports: any;
}

declare module 'storycap/lib/shared/screenshot-options-helper.test' {
  declare module.exports: any;
}

declare module 'storycap/lib/shared/types' {
  declare module.exports: any;
}

declare module 'storycap/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storycap/lib/client/is-screenshot.js' {
  declare module.exports: $Exports<'storycap/lib/client/is-screenshot'>;
}
declare module 'storycap/lib/client/register.js' {
  declare module.exports: $Exports<'storycap/lib/client/register'>;
}
declare module 'storycap/lib/client/trigger-screenshot.js' {
  declare module.exports: $Exports<'storycap/lib/client/trigger-screenshot'>;
}
declare module 'storycap/lib/client/with-screenshot.js' {
  declare module.exports: $Exports<'storycap/lib/client/with-screenshot'>;
}
declare module 'storycap/lib/index' {
  declare module.exports: $Exports<'storycap/lib'>;
}
declare module 'storycap/lib/index.js' {
  declare module.exports: $Exports<'storycap/lib'>;
}
declare module 'storycap/lib/node/capturing-browser.js' {
  declare module.exports: $Exports<'storycap/lib/node/capturing-browser'>;
}
declare module 'storycap/lib/node/cli.js' {
  declare module.exports: $Exports<'storycap/lib/node/cli'>;
}
declare module 'storycap/lib/node/errors.js' {
  declare module.exports: $Exports<'storycap/lib/node/errors'>;
}
declare module 'storycap/lib/node/file.js' {
  declare module.exports: $Exports<'storycap/lib/node/file'>;
}
declare module 'storycap/lib/node/logger.js' {
  declare module.exports: $Exports<'storycap/lib/node/logger'>;
}
declare module 'storycap/lib/node/main.js' {
  declare module.exports: $Exports<'storycap/lib/node/main'>;
}
declare module 'storycap/lib/node/screenshot-service.js' {
  declare module.exports: $Exports<'storycap/lib/node/screenshot-service'>;
}
declare module 'storycap/lib/node/types.js' {
  declare module.exports: $Exports<'storycap/lib/node/types'>;
}
declare module 'storycap/lib/shared/screenshot-options-helper.js' {
  declare module.exports: $Exports<'storycap/lib/shared/screenshot-options-helper'>;
}
declare module 'storycap/lib/shared/screenshot-options-helper.test.js' {
  declare module.exports: $Exports<'storycap/lib/shared/screenshot-options-helper.test'>;
}
declare module 'storycap/lib/shared/types.js' {
  declare module.exports: $Exports<'storycap/lib/shared/types'>;
}
declare module 'storycap/register.js' {
  declare module.exports: $Exports<'storycap/register'>;
}
