// flow-typed signature: bb212f69d6a4a4de0b75933e00c58ab4
// flow-typed version: <<STUB>>/text-width_v1.2.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-width'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-width' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'text-width/index' {
  declare module.exports: $Exports<'text-width'>;
}
declare module 'text-width/index.js' {
  declare module.exports: $Exports<'text-width'>;
}
