// flow-typed signature: c4e9a1866352d0da147d105956504d82
// flow-typed version: <<STUB>>/tinycolor2_v1.4.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tinycolor2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tinycolor2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tinycolor2/demo/jquery-1.9.1' {
  declare module.exports: any;
}

declare module 'tinycolor2/dist/tinycolor-min' {
  declare module.exports: any;
}

declare module 'tinycolor2/Gruntfile' {
  declare module.exports: any;
}

declare module 'tinycolor2/test/qunit' {
  declare module.exports: any;
}

declare module 'tinycolor2/test/test' {
  declare module.exports: any;
}

declare module 'tinycolor2/tinycolor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tinycolor2/demo/jquery-1.9.1.js' {
  declare module.exports: $Exports<'tinycolor2/demo/jquery-1.9.1'>;
}
declare module 'tinycolor2/dist/tinycolor-min.js' {
  declare module.exports: $Exports<'tinycolor2/dist/tinycolor-min'>;
}
declare module 'tinycolor2/Gruntfile.js' {
  declare module.exports: $Exports<'tinycolor2/Gruntfile'>;
}
declare module 'tinycolor2/test/qunit.js' {
  declare module.exports: $Exports<'tinycolor2/test/qunit'>;
}
declare module 'tinycolor2/test/test.js' {
  declare module.exports: $Exports<'tinycolor2/test/test'>;
}
declare module 'tinycolor2/tinycolor.js' {
  declare module.exports: $Exports<'tinycolor2/tinycolor'>;
}
