// flow-typed signature: f106fc9e95396281807cabd12b98c47b
// flow-typed version: <<STUB>>/unist-util-visit_v^1.4.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unist-util-visit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unist-util-visit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'unist-util-visit/index' {
  declare module.exports: $Exports<'unist-util-visit'>;
}
declare module 'unist-util-visit/index.js' {
  declare module.exports: $Exports<'unist-util-visit'>;
}
