// flow-typed signature: d1c360566fa87136c026ad5cdba56a99
// flow-typed version: <<STUB>>/wasm-lz4_v0.4.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wasm-lz4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wasm-lz4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wasm-lz4/post' {
  declare module.exports: any;
}

declare module 'wasm-lz4/pre' {
  declare module.exports: any;
}

declare module 'wasm-lz4/wasm-lz4' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wasm-lz4/index' {
  declare module.exports: $Exports<'wasm-lz4'>;
}
declare module 'wasm-lz4/index.js' {
  declare module.exports: $Exports<'wasm-lz4'>;
}
declare module 'wasm-lz4/post.js' {
  declare module.exports: $Exports<'wasm-lz4/post'>;
}
declare module 'wasm-lz4/pre.js' {
  declare module.exports: $Exports<'wasm-lz4/pre'>;
}
declare module 'wasm-lz4/wasm-lz4.js' {
  declare module.exports: $Exports<'wasm-lz4/wasm-lz4'>;
}
