// flow-typed signature: 71a622fbeae9c404feb3705f24f40931
// flow-typed version: <<STUB>>/webpack-hot-middleware_v2.24.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-hot-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-hot-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-hot-middleware/client-overlay' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/client' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/helpers' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/middleware' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/process-update' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-hot-middleware/client-overlay.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/client-overlay'>;
}
declare module 'webpack-hot-middleware/client.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/client'>;
}
declare module 'webpack-hot-middleware/helpers.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/helpers'>;
}
declare module 'webpack-hot-middleware/middleware.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/middleware'>;
}
declare module 'webpack-hot-middleware/process-update.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/process-update'>;
}
