// flow-typed signature: fca155539328607e70dd39bfdb52ce8a
// flow-typed version: <<STUB>>/webpack-dev-server_v^3.7.1/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-server/bin/options' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/bin/webpack-dev-server' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/clients/BaseClient' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/clients/SockJSClient' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/clients/WebsocketClient' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/index.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/live.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/overlay' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/socket' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/sockjs.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/createSocketUrl' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/getCurrentScriptSource' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/log' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/reloadApp' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/utils/sendMessage' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/Server' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/servers/BaseServer' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/servers/SockJSServer' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/servers/WebsocketServer' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/addEntries' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/colors' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/createCertificate' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/createConfig' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/createDomain' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/createLogger' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/defaultPort' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/defaultTo' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/findPort' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/getCertificate' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/getSocketServerImplementation' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/getVersions' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/processOptions' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/routes' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/runBonjour' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/runOpen' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/setupExitSignals' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/status' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/tryParseInt' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/updateCompiler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-server/bin/options.js' {
  declare module.exports: $Exports<'webpack-dev-server/bin/options'>;
}
declare module 'webpack-dev-server/bin/webpack-dev-server.js' {
  declare module.exports: $Exports<'webpack-dev-server/bin/webpack-dev-server'>;
}
declare module 'webpack-dev-server/client/clients/BaseClient.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/clients/BaseClient'>;
}
declare module 'webpack-dev-server/client/clients/SockJSClient.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/clients/SockJSClient'>;
}
declare module 'webpack-dev-server/client/clients/WebsocketClient.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/clients/WebsocketClient'>;
}
declare module 'webpack-dev-server/client/index.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/index.bundle'>;
}
declare module 'webpack-dev-server/client/index' {
  declare module.exports: $Exports<'webpack-dev-server/client'>;
}
declare module 'webpack-dev-server/client/index.js' {
  declare module.exports: $Exports<'webpack-dev-server/client'>;
}
declare module 'webpack-dev-server/client/live.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/live.bundle'>;
}
declare module 'webpack-dev-server/client/overlay.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/overlay'>;
}
declare module 'webpack-dev-server/client/socket.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/socket'>;
}
declare module 'webpack-dev-server/client/sockjs.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/sockjs.bundle'>;
}
declare module 'webpack-dev-server/client/utils/createSocketUrl.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/createSocketUrl'>;
}
declare module 'webpack-dev-server/client/utils/getCurrentScriptSource.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/getCurrentScriptSource'>;
}
declare module 'webpack-dev-server/client/utils/log.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/log'>;
}
declare module 'webpack-dev-server/client/utils/reloadApp.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/reloadApp'>;
}
declare module 'webpack-dev-server/client/utils/sendMessage.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/utils/sendMessage'>;
}
declare module 'webpack-dev-server/lib/Server.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/Server'>;
}
declare module 'webpack-dev-server/lib/servers/BaseServer.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/servers/BaseServer'>;
}
declare module 'webpack-dev-server/lib/servers/SockJSServer.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/servers/SockJSServer'>;
}
declare module 'webpack-dev-server/lib/servers/WebsocketServer.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/servers/WebsocketServer'>;
}
declare module 'webpack-dev-server/lib/utils/addEntries.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/addEntries'>;
}
declare module 'webpack-dev-server/lib/utils/colors.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/colors'>;
}
declare module 'webpack-dev-server/lib/utils/createCertificate.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/createCertificate'>;
}
declare module 'webpack-dev-server/lib/utils/createConfig.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/createConfig'>;
}
declare module 'webpack-dev-server/lib/utils/createDomain.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/createDomain'>;
}
declare module 'webpack-dev-server/lib/utils/createLogger.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/createLogger'>;
}
declare module 'webpack-dev-server/lib/utils/defaultPort.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/defaultPort'>;
}
declare module 'webpack-dev-server/lib/utils/defaultTo.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/defaultTo'>;
}
declare module 'webpack-dev-server/lib/utils/findPort.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/findPort'>;
}
declare module 'webpack-dev-server/lib/utils/getCertificate.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/getCertificate'>;
}
declare module 'webpack-dev-server/lib/utils/getSocketServerImplementation.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/getSocketServerImplementation'>;
}
declare module 'webpack-dev-server/lib/utils/getVersions.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/getVersions'>;
}
declare module 'webpack-dev-server/lib/utils/processOptions.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/processOptions'>;
}
declare module 'webpack-dev-server/lib/utils/routes.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/routes'>;
}
declare module 'webpack-dev-server/lib/utils/runBonjour.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/runBonjour'>;
}
declare module 'webpack-dev-server/lib/utils/runOpen.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/runOpen'>;
}
declare module 'webpack-dev-server/lib/utils/setupExitSignals.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/setupExitSignals'>;
}
declare module 'webpack-dev-server/lib/utils/status.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/status'>;
}
declare module 'webpack-dev-server/lib/utils/tryParseInt.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/tryParseInt'>;
}
declare module 'webpack-dev-server/lib/utils/updateCompiler.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/updateCompiler'>;
}
