// flow-typed signature: 157068669359914b93f5bfe5b4d35e89
// flow-typed version: <<STUB>>/worker-loader_v^2.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'worker-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'worker-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'worker-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'worker-loader/dist/Error' {
  declare module.exports: any;
}

declare module 'worker-loader/dist/index' {
  declare module.exports: any;
}

declare module 'worker-loader/dist/workers/index' {
  declare module.exports: any;
}

declare module 'worker-loader/dist/workers/InlineWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'worker-loader/dist/cjs.js' {
  declare module.exports: $Exports<'worker-loader/dist/cjs'>;
}
declare module 'worker-loader/dist/Error.js' {
  declare module.exports: $Exports<'worker-loader/dist/Error'>;
}
declare module 'worker-loader/dist/index.js' {
  declare module.exports: $Exports<'worker-loader/dist/index'>;
}
declare module 'worker-loader/dist/workers/index.js' {
  declare module.exports: $Exports<'worker-loader/dist/workers/index'>;
}
declare module 'worker-loader/dist/workers/InlineWorker.js' {
  declare module.exports: $Exports<'worker-loader/dist/workers/InlineWorker'>;
}
