// flow-typed signature: 5d012d5a2c468b314fc4359cd5534945
// flow-typed version: <<STUB>>/@babel/plugin-transform-modules-commonjs_v^7.2.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-modules-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-modules-commonjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-modules-commonjs/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-modules-commonjs/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-commonjs/lib'>;
}
declare module '@babel/plugin-transform-modules-commonjs/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-commonjs/lib'>;
}
