// @flow
//
//  Copyright (c) 2019-present, Cruise LLC
//
//  This source code is licensed under the Apache License, Version 2.0,
//  found in the LICENSE file in the root directory of this source tree.
//  You may not use this file except in compliance with the License.
export const ros_lib_filename = "ros/index.d.ts";
export const ros_lib_dts = `
  // Placeholder module declaration. Once any bag-like data source is added to
  // Webviz, this module will be autogenerated.
  declare module "ros";
`;
