// flow-typed signature: 49af2077df4e71f3c18335ecb2988c7c
// flow-typed version: <<STUB>>/@mapbox/rehype-prism_v^0.3.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/rehype-prism'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/rehype-prism' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/rehype-prism/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/rehype-prism/index' {
  declare module.exports: $Exports<'@mapbox/rehype-prism'>;
}
declare module '@mapbox/rehype-prism/index.js' {
  declare module.exports: $Exports<'@mapbox/rehype-prism'>;
}
declare module '@mapbox/rehype-prism/test.js' {
  declare module.exports: $Exports<'@mapbox/rehype-prism/test'>;
}
