// flow-typed signature: ad17e5337afe7bfe29a7e19f3ba6d559
// flow-typed version: <<STUB>>/@storybook/addon-knobs_v^4.0.12/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-knobs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-knobs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-knobs/angular' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/__tests__/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/__tests__/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/__tests__/RadioButtons' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/__tests__/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/PropForm' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Boolean' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Button' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Color' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Date' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Files' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Number' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Radio' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Text' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/deprecated' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/KnobManager' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/KnobManager.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/KnobStore' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/registerKnobs' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/html' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/marko' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/mithril' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/polymer' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/__tests__/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/__tests__/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/__tests__/RadioButtons' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/__tests__/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/PropForm' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Boolean' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Button' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Color' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Date' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Files' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Number' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Radio' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/components/types/Text' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/deprecated' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/KnobManager' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/KnobManager.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/KnobStore' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/src/registerKnobs' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-knobs/angular.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/angular'>;
}
declare module '@storybook/addon-knobs/dist/components/__tests__/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/__tests__/Array'>;
}
declare module '@storybook/addon-knobs/dist/components/__tests__/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/__tests__/Panel'>;
}
declare module '@storybook/addon-knobs/dist/components/__tests__/RadioButtons.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/__tests__/RadioButtons'>;
}
declare module '@storybook/addon-knobs/dist/components/__tests__/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/__tests__/Select'>;
}
declare module '@storybook/addon-knobs/dist/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/Panel'>;
}
declare module '@storybook/addon-knobs/dist/components/PropForm.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/PropForm'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Array'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Boolean.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Boolean'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Button.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Button'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Color.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Color'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Date.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Date'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Files.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Files'>;
}
declare module '@storybook/addon-knobs/dist/components/types/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types'>;
}
declare module '@storybook/addon-knobs/dist/components/types/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Number.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Number'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Object'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Radio.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Radio'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Select'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Text.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Text'>;
}
declare module '@storybook/addon-knobs/dist/deprecated.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/deprecated'>;
}
declare module '@storybook/addon-knobs/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist'>;
}
declare module '@storybook/addon-knobs/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist'>;
}
declare module '@storybook/addon-knobs/dist/KnobManager.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/KnobManager'>;
}
declare module '@storybook/addon-knobs/dist/KnobManager.test.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/KnobManager.test'>;
}
declare module '@storybook/addon-knobs/dist/KnobStore.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/KnobStore'>;
}
declare module '@storybook/addon-knobs/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/register'>;
}
declare module '@storybook/addon-knobs/dist/registerKnobs.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/registerKnobs'>;
}
declare module '@storybook/addon-knobs/html.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/html'>;
}
declare module '@storybook/addon-knobs/marko.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/marko'>;
}
declare module '@storybook/addon-knobs/mithril.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/mithril'>;
}
declare module '@storybook/addon-knobs/polymer.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/polymer'>;
}
declare module '@storybook/addon-knobs/react.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/react'>;
}
declare module '@storybook/addon-knobs/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/register'>;
}
declare module '@storybook/addon-knobs/src/components/__tests__/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/__tests__/Array'>;
}
declare module '@storybook/addon-knobs/src/components/__tests__/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/__tests__/Panel'>;
}
declare module '@storybook/addon-knobs/src/components/__tests__/RadioButtons.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/__tests__/RadioButtons'>;
}
declare module '@storybook/addon-knobs/src/components/__tests__/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/__tests__/Select'>;
}
declare module '@storybook/addon-knobs/src/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/Panel'>;
}
declare module '@storybook/addon-knobs/src/components/PropForm.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/PropForm'>;
}
declare module '@storybook/addon-knobs/src/components/types/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Array'>;
}
declare module '@storybook/addon-knobs/src/components/types/Boolean.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Boolean'>;
}
declare module '@storybook/addon-knobs/src/components/types/Button.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Button'>;
}
declare module '@storybook/addon-knobs/src/components/types/Color.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Color'>;
}
declare module '@storybook/addon-knobs/src/components/types/Date.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Date'>;
}
declare module '@storybook/addon-knobs/src/components/types/Files.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Files'>;
}
declare module '@storybook/addon-knobs/src/components/types/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types'>;
}
declare module '@storybook/addon-knobs/src/components/types/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types'>;
}
declare module '@storybook/addon-knobs/src/components/types/Number.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Number'>;
}
declare module '@storybook/addon-knobs/src/components/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Object'>;
}
declare module '@storybook/addon-knobs/src/components/types/Radio.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Radio'>;
}
declare module '@storybook/addon-knobs/src/components/types/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Select'>;
}
declare module '@storybook/addon-knobs/src/components/types/Text.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/components/types/Text'>;
}
declare module '@storybook/addon-knobs/src/deprecated.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/deprecated'>;
}
declare module '@storybook/addon-knobs/src/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src'>;
}
declare module '@storybook/addon-knobs/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src'>;
}
declare module '@storybook/addon-knobs/src/KnobManager.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/KnobManager'>;
}
declare module '@storybook/addon-knobs/src/KnobManager.test.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/KnobManager.test'>;
}
declare module '@storybook/addon-knobs/src/KnobStore.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/KnobStore'>;
}
declare module '@storybook/addon-knobs/src/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/register'>;
}
declare module '@storybook/addon-knobs/src/registerKnobs.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/src/registerKnobs'>;
}
declare module '@storybook/addon-knobs/vue.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/vue'>;
}
