// flow-typed signature: 6a00018bbdbd6482e8fdd89d58ff6c0c
// flow-typed version: <<STUB>>/@storybook/addons_v^4.0.12/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addons/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/make-decorator' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/make-decorator.test' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/storybook-channel-mock' {
  declare module.exports: any;
}

declare module '@storybook/addons/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addons/src/make-decorator' {
  declare module.exports: any;
}

declare module '@storybook/addons/src/make-decorator.test' {
  declare module.exports: any;
}

declare module '@storybook/addons/src/storybook-channel-mock' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addons/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/index'>;
}
declare module '@storybook/addons/dist/make-decorator.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/make-decorator'>;
}
declare module '@storybook/addons/dist/make-decorator.test.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/make-decorator.test'>;
}
declare module '@storybook/addons/dist/storybook-channel-mock.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/storybook-channel-mock'>;
}
declare module '@storybook/addons/src/index.js' {
  declare module.exports: $Exports<'@storybook/addons/src/index'>;
}
declare module '@storybook/addons/src/make-decorator.js' {
  declare module.exports: $Exports<'@storybook/addons/src/make-decorator'>;
}
declare module '@storybook/addons/src/make-decorator.test.js' {
  declare module.exports: $Exports<'@storybook/addons/src/make-decorator.test'>;
}
declare module '@storybook/addons/src/storybook-channel-mock.js' {
  declare module.exports: $Exports<'@storybook/addons/src/storybook-channel-mock'>;
}
