name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm bootstrap & build
      run: |
        npm run bootstrap
        npm run build --if-present
      env:
        CI: true
    - uses: mr-smithers-excellent/docker-build-push@v1.0
    with:
      image: webwiz
      tag: latest
      registry: docker.pkg.github.com/enwaytech/webviz/
      dockerfile: Dockerfile.ci
      username: stefan-enway
